export const COMPANY_SECTORS = [
  "Agricultura e Pecuária",
  "Alimentação e Bebidas",
  "Automóvel e Reparação",
  "Aviação",
  "Banca e Seguros",
  "Comércio e Retalho",
  "Construção Civil",
  "Consultoria e Serviços Profissionais",
  "Defesa e Segurança",
  "Distribuição e Logística",
  "Educação",
  "Energia e Electricidade",
  "Engenharia",
  "Farmacêutico e Saúde",
  "Hotelaria e Turismo",
  "Imobiliário",
  "Importação e Exportação",
  "Indústria Transformadora",
  "Marítimo e Portuário",
  "Media e Comunicação",
  "Mineração",
  "Petróleo e Gás",
  "Pesca e Aquicultura",
  "Químico e Petroquímico",
  "Recursos Humanos",
  "Saúde",
  "Serviços Públicos",
  "Tecnologia de Informação",
  "Telecomunicações",
  "Textil e Vestuário",
  "Transporte e Logística",
  "Ambiente e Saneamento",
  "Metalurgia e Siderurgia",
  "Construção de Infra-estruturas",
  "Obras Públicas",
] as const;

export const JOB_TITLES = [
  "Administrador",
  "Assistente Comercial",
  "Comprador",
  "Consultor Comercial",
  "Contabilista",
  "Coordenador",
  "Director Comercial",
  "Director de Compras",
  "Director de Operações",
  "Director de Projetos",
  "Director de Recursos Humanos",
  "Director Executivo",
  "Director Financeiro",
  "Director Geral",
  "Director Técnico",
  "Engenheiro",
  "Gerente",
  "Gestor de Compras",
  "Gestor de Frota",
  "Gestor de Logística",
  "Gestor de Manutenção",
  "Gestor de Operações",
  "Proprietário",
  "Representante Comercial",
  "Responsável de Frota",
  "Responsável de Manutenção",
  "Sócio",
  "Supervisor",
  "Técnico Comercial",
  "Técnico de Manutenção",
  "Chefe de Departamento",
  "Chefe de Secção",
  "Gestor de Armazém",
  "Analista de Compras",
  "Coordenador de Projetos",
] as const;
