export const COMPANY_SECTORS = [
  "Construção Civil",
  "Transportes e Logística",
  "Indústria",
  "Comércio",
  "Agricultura",
  "Pescas",
  "Mineração",
  "Petróleo e Gás",
  "Serviços",
  "Hotelaria e Restauração",
  "Saúde",
  "Educação",
  "Sector Público",
  "Outros",
] as const;

export const JOB_TITLES = [
  "Director Geral",
  "Director Comercial",
  "Director Financeiro",
  "Director de Operações",
  "Gestor",
  "Coordenador",
  "Supervisor",
  "Técnico",
  "Administrativo",
  "Comprador/Procurement",
  "Proprietário/Sócio",
  "Outros",
  "Estratégico/Executivo",
  "Direcção",
  "Gestão Intermédia",
  "Supervisão",
  "Técnico/Especialista",
] as const;
