import type { DashboardStats, Lead } from "./types";

export const MOCK_STATS: DashboardStats = {
  totalLeads: 247,
  qualifiedLeads: 89,
  potentialClients: 156,
  potentialPartners: 34,
  closedDeals: 12,
};

export const MOCK_LEADS: Lead[] = [
  {
    id: "LD-001",
    company: "TransAngola Lda",
    contactName: "Manuel Santos",
    email: "manuel.santos@transangola.ao",
    phone: "+244 923 456 789",
    type: "Potencial Cliente",
    product: "Frota+",
    stage: "Qualificada",
    interestLevel: "Muito Alto",
    businessPotential: "Alto",
    assignedTo: "Ana Costa",
    createdAt: "2026-06-14",
    nextFollowUp: "2026-06-17",
    lastContact: "2026-06-15",
    notes: "Frota de 45 veículos. Interesse em demonstração.",
  },
  {
    id: "LD-002",
    company: "Construções Bengo SA",
    contactName: "Isabel Ferreira",
    email: "isabel.ferreira@bengo.ao",
    phone: "+244 912 345 678",
    type: "Potencial Cliente",
    product: "Cartão Combustível",
    stage: "Proposta Enviada",
    interestLevel: "Alto",
    businessPotential: "Alto",
    assignedTo: "Carlos Mendes",
    createdAt: "2026-06-13",
    nextFollowUp: "2026-06-16",
    lastContact: "2026-06-14",
    notes: "Aguarda aprovação da direcção financeira.",
  },
  {
    id: "LD-003",
    company: "Logística Huíla",
    contactName: "Paulo Nunes",
    email: "p.nunes@loghuila.ao",
    phone: "+244 934 567 890",
    type: "Cliente",
    product: "Lubrificantes",
    stage: "Negociação",
    interestLevel: "Alto",
    businessPotential: "Médio",
    assignedTo: "Ana Costa",
    createdAt: "2026-06-12",
    nextFollowUp: "2026-06-18",
    lastContact: "2026-06-15",
    notes: "Cliente existente. Expansão de contrato.",
  },
  {
    id: "LD-004",
    company: "Agro Norte",
    contactName: "Teresa Campos",
    email: "teresa@agronorte.ao",
    phone: "+244 945 678 901",
    type: "Parceiro",
    product: "Parcerias",
    stage: "Contactada",
    interestLevel: "Médio",
    businessPotential: "Alto",
    assignedTo: "Miguel Silva",
    createdAt: "2026-06-14",
    nextFollowUp: "2026-06-17",
    lastContact: "2026-06-14",
    notes: "Interesse em parceria de distribuição regional.",
  },
  {
    id: "LD-005",
    company: "Mineração Central",
    contactName: "João Baptista",
    email: "jbaptista@mineracaocentral.ao",
    phone: "+244 956 789 012",
    type: "Potencial Cliente",
    product: "Soluções Empresariais",
    stage: "Captada",
    interestLevel: "Médio",
    businessPotential: "Alto",
    assignedTo: "Carlos Mendes",
    createdAt: "2026-06-15",
    nextFollowUp: "2026-06-16",
    lastContact: null,
    notes: "Registo via QR Code no stand FILDA.",
  },
  {
    id: "LD-006",
    company: "Transportes Luanda",
    contactName: "Rosa Domingos",
    email: "rosa.d@transluanda.ao",
    phone: "+244 967 890 123",
    type: "Potencial Cliente",
    product: "Frota+",
    stage: "Convertida",
    interestLevel: "Muito Alto",
    businessPotential: "Alto",
    assignedTo: "Ana Costa",
    createdAt: "2026-06-10",
    nextFollowUp: null,
    lastContact: "2026-06-15",
    notes: "Contrato assinado. Onboarding agendado.",
  },
  {
    id: "LD-007",
    company: "Indústrias do Cuanza",
    contactName: "Fernando Lima",
    email: "f.lima@idc.ao",
    phone: "+244 978 901 234",
    type: "Potencial Cliente",
    product: "Combustíveis",
    stage: "Qualificada",
    interestLevel: "Alto",
    businessPotential: "Médio",
    assignedTo: "Miguel Silva",
    createdAt: "2026-06-13",
    nextFollowUp: "2026-06-19",
    lastContact: "2026-06-14",
    notes: "Necessita proposta para 3 unidades fabris.",
  },
  {
    id: "LD-008",
    company: "Grupo Energia+",
    contactName: "Catarina Ribeiro",
    email: "c.ribeiro@energiamais.ao",
    phone: "+244 989 012 345",
    type: "Investidor",
    product: "Parcerias",
    stage: "Contactada",
    interestLevel: "Baixo",
    businessPotential: "Médio",
    assignedTo: "Carlos Mendes",
    createdAt: "2026-06-15",
    nextFollowUp: "2026-06-20",
    lastContact: "2026-06-15",
    notes: "Primeiro contacto na FILDA. Enviar apresentação institucional.",
  },
];

export const PIPELINE_COUNTS = {
  Captada: 42,
  Contactada: 38,
  Qualificada: 56,
  "Proposta Enviada": 34,
  Negociação: 28,
  Convertida: 12,
};
